/** Arabic UI strings keyed by the English source text. Draft translations — have them reviewed by a native finance/tax reviewer. */
export const AR: Record<string, string> = {
  "'Tax Invoice' heading": "عنوان «فاتورة ضريبية»",
  "'Tax Invoice' heading present": "يوجد عنوان «فاتورة ضريبية»",
  "(Overridden by user.)": "(عدّله المستخدم.)",
  "0% band": "شريحة 0%",
  "0% on first AED 375,000": "0% على أول 375,000 درهم",
  "1 · Drop a purchase invoice": "1 · أفلت فاتورة مشتريات",
  "12 months": "12 شهرًا",
  "1–30": "1–30",
  "2 · Extracted data": "2 · البيانات المستخرجة",
  "28 days after period": "28 يومًا بعد نهاية الفترة",
  "3 · FTA compliance & fraud checks": "3 · فحوص الامتثال للهيئة والاحتيال",
  "30 days": "30 يومًا",
  "31–60": "31–60",
  "4 · Classification": "4 · التصنيف",
  "5 · Proposed journal entry": "5 · قيد اليومية المقترح",
  "5-corner flow status": "حالة مسار الأركان الخمسة",
  "50% deductible": "قابل للخصم بنسبة 50%",
  "50% deductible (Art 32)": "قابل للخصم 50% (المادة 32)",
  "61–90": "61–90",
  "9% above AED 375,000": "9% على ما يزيد عن 375,000 درهم",
  "9% on AED {amt}": "9% على {amt} درهم",
  "90 days": "90 يومًا",
  "90+": "+90",
  "ADNOC fuel": "وقود أدنوك",
  "AI": "ذكاء اصطناعي",
  "AI CFO insight · {a} vs {b}": "رؤية المدير المالي الذكي · {a} مقابل {b}",
  "AI auto-approve rules": "قواعد الاعتماد التلقائي بالذكاء الاصطناعي",
  "AI automation": "أتمتة الذكاء الاصطناعي",
  "AI checks: TRN, VAT rate, export / zero-rating look consistent": "فحوص الذكاء الاصطناعي: الرقم الضريبي ونسبة الضريبة والتصدير/النسبة الصفرية متسقة",
  "AI events": "أحداث الذكاء الاصطناعي",
  "AI extraction": "استخراج بالذكاء الاصطناعي",
  "AI extraction & coding": "الاستخراج والترميز الذكي",
  "AI involvement · {n}%": "مشاركة الذكاء الاصطناعي · {n}%",
  "AI may post only below these thresholds AND with low risk — otherwise a human approves": "لا يرحّل الذكاء الاصطناعي إلا دون هذه الحدود ومع مخاطر منخفضة — وإلا يعتمد شخص مختص",
  "AI pre-filing review": "مراجعة ذكية قبل التقديم",
  "AI proposes": "الذكاء الاصطناعي يقترح",
  "AI proposes the account, VAT code and CT treatment with a confidence score": "يقترح الذكاء الاصطناعي الحساب ورمز الضريبة ومعاملة ضريبة الشركات مع درجة ثقة",
  "AI suggestions ready": "اقتراحات الذكاء الاصطناعي جاهزة",
  "AI-coded": "مرمّزة آليًا",
  "AI-native UAE accounting": "محاسبة إماراتية مدعومة بالذكاء الاصطناعي",
  "AI-prepared": "أعدّها الذكاء الاصطناعي",
  "AP": "الدائنون",
  "AR": "المدينون",
  "ASSET": "أصل",
  "Account": "الحساب",
  "Account ledger": "دفتر الحساب",
  "Accountant": "المحاسب",
  "Accounting": "المحاسبة",
  "Accounting profit": "الربح المحاسبي",
  "Accounting profit (YTD)": "الربح المحاسبي (منذ بداية السنة)",
  "Accounting profit before tax (IFRS)": "الربح المحاسبي قبل الضريبة (IFRS)",
  "Across all clients": "عبر جميع العملاء",
  "Action": "الإجراء",
  "Actions": "الإجراءات",
  "Active clients": "العملاء النشطون",
  "Add line": "إضافة سطر",
  "Add:": "يُضاف:",
  "Advertising / marketing vendor → Marketing and advertising.": "مورد إعلان/تسويق ← التسويق والإعلان.",
  "All": "الكل",
  "All captured invoices, journals and settings in this browser will be replaced with the original demo data.": "سيتم استبدال جميع الفواتير والقيود والإعدادات في هذا المتصفح ببيانات العرض الأصلية.",
  "All clients": "جميع العملاء",
  "All posted journals to date": "جميع القيود المرحّلة حتى تاريخه",
  "Amount": "المبلغ",
  "Annualised revenue": "الإيرادات السنوية المقدّرة",
  "Append-only": "إضافة فقط",
  "Append-only log: who, what, when, AI involvement — feeds the FTA Audit File and statutory audit.": "سجل للإضافة فقط: من وماذا ومتى ودور الذكاء الاصطناعي — يغذي ملف تدقيق الهيئة والتدقيق القانوني.",
  "Appoint e-invoicing ASP (revenue < AED 50m)": "تعيين مزوّد خدمة الفوترة الإلكترونية المعتمد (إيرادات < 50 مليون درهم)",
  "Approvals": "الاعتمادات",
  "Approve & post": "اعتماد وترحيل",
  "Approved": "معتمد",
  "Approved & posted": "اعتُمد ورُحّل",
  "Approved by": "اعتمده",
  "Art 59 Exec. Regulation + duplicate / TRN / arithmetic": "المادة 59 من اللائحة التنفيذية + التكرار / الرقم الضريبي / الحساب",
  "Art 59 · maker-checker": "المادة 59 · مُعِدّ ومُراجِع",
  "Art 59(1)(a)": "المادة 59(1)(أ)",
  "Article 59 compliance check": "فحص الامتثال للمادة 59",
  "As at 30 September 2026 · AED": "كما في 30 سبتمبر 2026 · درهم",
  "Ask a question": "اطرح سؤالًا",
  "Ask anything about {org}'s numbers": "اسأل أي شيء عن أرقام {org}",
  "Ask your books": "اسأل دفاترك",
  "Assets": "الأصول",
  "Assets = Liabilities + Equity ✓ balanced to the fils": "الأصول = الخصوم + حقوق الملكية ✓ متوازنة حتى الفلس",
  "Assets ≠ Liabilities + Equity": "الأصول ≠ الخصوم + حقوق الملكية",
  "Audit": "التدقيق",
  "Audit trail": "سجل التدقيق",
  "Auto-approve on": "الاعتماد التلقائي مفعّل",
  "Auto-approved": "معتمد تلقائيًا",
  "Auto-approved & posted {ref} — within tenant thresholds": "اعتُمد ورُحّل {ref} تلقائيًا — ضمن حدود المنشأة",
  "Auto-classified from supplier and description patterns.": "صُنّف تلقائيًا من أنماط المورد والوصف.",
  "Auto-match": "مطابقة تلقائية",
  "Auto-posted": "رُحّل تلقائيًا",
  "Awaiting approval": "بانتظار الاعتماد",
  "BANK": "بنك",
  "Backup downloaded": "تم تنزيل النسخة الاحتياطية",
  "Backup restored": "تمت استعادة النسخة الاحتياطية",
  "Balance": "الرصيد",
  "Balance sheet": "الميزانية العمومية",
  "Balance sheet check": "فحص الميزانية العمومية",
  "Balanced": "متوازن",
  "Balances ✓": "متوازنة ✓",
  "Bank auto-match": "مطابقة بنكية تلقائية",
  "Bank fee → Bank charges.": "رسوم بنكية ← الرسوم البنكية.",
  "Bank feed": "التغذية البنكية",
  "Bank import": "استيراد بنكي",
  "Bank line categorised": "تم تصنيف السطر البنكي",
  "Bank line posted": "تم ترحيل السطر البنكي",
  "Bank lines": "أسطر بنكية",
  "Bank narrative pattern": "نمط وصف العملية البنكية",
  "Bank reconciliation": "التسوية البنكية",
  "Bank — current account (AED) · September 2026 statement": "البنك — الحساب الجاري (درهم) · كشف سبتمبر 2026",
  "Basis": "الأساس",
  "Bilingual tax invoices · VAT treatment checks · PINT AE (UBL 2.1) generation & ASP transmission (sandbox)": "فواتير ضريبية ثنائية اللغة · فحوص المعاملة الضريبية · إنشاء PINT AE (UBL 2.1) والإرسال عبر مزوّد الخدمة (تجريبي)",
  "Bilingual tax invoices; PINT AE e-invoices via ASP": "فواتير ضريبية ثنائية اللغة؛ فواتير PINT AE إلكترونية عبر مزوّد الخدمة",
  "Blocked": "محظورة",
  "Blocked / non-recoverable": "محظورة / غير قابلة للاسترداد",
  "Blocked input VAT (not claimed)": "ضريبة مدخلات محظورة (غير مطالب بها)",
  "Box": "الخانة",
  "Box 12 · Total due tax": "الخانة 12 · إجمالي الضريبة المستحقة",
  "Box 13 · Recoverable tax": "الخانة 13 · الضريبة القابلة للاسترداد",
  "Box 13 ÷ Box 12 · Q3": "الخانة 13 ÷ الخانة 12 · الربع الثالث",
  "Box 14 · Payable": "الخانة 14 · مستحقة الدفع",
  "Box 14 · Refundable": "الخانة 14 · قابلة للاسترداد",
  "Box 1a–1g": "الخانات 1أ–1ز",
  "Box 8 total": "إجمالي الخانة 8",
  "Box mapping must be re-verified against the live EmaraTax VAT 201 form before filing — VERIFY. Filing is done by the tax agent on EmaraTax after partner review.": "يجب التحقق من ربط الخانات مقابل نموذج VAT 201 الحالي في «إمارات تاكس» قبل التقديم — للتحقق. يقدّم الوكيل الضريبي الإقرار عبر «إمارات تاكس» بعد مراجعة الشريك.",
  "Buyer": "المشتري",
  "Buyer ASP": "مزوّد المشتري",
  "Buyer TRN required for UAE B2B tax invoices": "الرقم الضريبي للمشتري مطلوب في الفواتير الضريبية بين الشركات في الإمارات",
  "CLIENT_FINANCE": "مالية العميل",
  "CLIENT_OWNER": "مالك العميل",
  "COGS": "تكلفة المبيعات",
  "CSV rows": "صفوف CSV",
  "CT": "ضريبة الشركات",
  "CT FY26": "ضريبة الشركات 2026",
  "CT estimate": "تقدير ضريبة الشركات",
  "CT estimate FY26": "تقدير ضريبة الشركات 2026",
  "CT payable": "ضريبة الشركات المستحقة",
  "CT rate / 0% band": "نسبة ضريبة الشركات / شريحة 0%",
  "CT regime": "نظام ضريبة الشركات",
  "CT return {fy} — file & pay": "إقرار ضريبة الشركات {fy} — التقديم والسداد",
  "Cancel": "إلغاء",
  "Capital / balance sheet": "رأسمالي / الميزانية",
  "Capture invoice": "التقاط فاتورة",
  "Capture invoices": "التقاط الفواتير",
  "Cash at bank": "النقد في البنك",
  "Classified": "مصنّفة",
  "Classify · VAT · CT tags": "تصنيف · ضريبة القيمة المضافة · وسوم ضريبة الشركات",
  "Classifying account, VAT & CT": "تصنيف الحساب والضريبة وضريبة الشركات",
  "Clear": "مسح",
  "Click to open →": "انقر للفتح ←",
  "Client": "العميل",
  "Client Finance": "مالية العميل",
  "Client Owner": "مالك العميل",
  "Client dinner": "عشاء عمل مع عميل",
  "Client entertainment": "ضيافة العملاء",
  "Client entertainment — 50% disallowed": "ضيافة العملاء — 50% غير قابلة للخصم",
  "Client is eligible for Small Business Relief (revenue ≤ AED 3m). Consider electing SBR.": "العميل مؤهل لإعفاء الأعمال الصغيرة (إيرادات ≤ 3 ملايين درهم). يُنصح باختياره.",
  "Client status board": "لوحة حالة العملاء",
  "Clients": "العملاء",
  "Clients and open items": "العملاء والبنود المفتوحة",
  "Close": "إغلاق",
  "Close menu": "إغلاق القائمة",
  "Closing balance": "الرصيد الختامي",
  "Code": "الرمز",
  "Commercial rent / tenancy description → Rent expense. Commercial rent is standard-rated.": "وصف إيجار تجاري ← مصروف الإيجار. الإيجار التجاري خاضع للنسبة الأساسية.",
  "Compliance calendar": "تقويم الامتثال",
  "Copy XML": "نسخ XML",
  "Corporate tax": "ضريبة الشركات",
  "Corporate tax (estimate, not yet booked)": "ضريبة الشركات (تقديرية، لم تُقيَّد بعد)",
  "Corporate tax computation": "احتساب ضريبة الشركات",
  "Corporate tax payable": "ضريبة الشركات المستحقة",
  "Cost of sales": "تكلفة المبيعات",
  "Credit": "دائن",
  "Currency": "العملة",
  "Current": "جارية",
  "Customer": "العميل",
  "Customer TRN": "الرقم الضريبي للعميل",
  "Customer country": "دولة العميل",
  "Customer name": "اسم العميل",
  "DELIVERED": "تم التسليم",
  "DRAFT": "مسودة",
  "Dashboard": "لوحة التحكم",
  "Data": "البيانات",
  "Date": "التاريخ",
  "Date of issue": "تاريخ الإصدار",
  "Date of supply": "تاريخ التوريد",
  "Deadline heat-map": "خريطة المواعيد النهائية",
  "Debit": "مدين",
  "Deductible": "قابل للخصم",
  "Demo data reset": "تمت إعادة تعيين بيانات العرض",
  "Description": "الوصف",
  "Description of goods / services": "وصف السلع / الخدمات",
  "Detail": "التفاصيل",
  "Deterministic checks + human approval above tenant thresholds": "فحوص قطعية + اعتماد بشري فوق حدود المنشأة",
  "Direction": "الاتجاه",
  "Disallowed": "غير قابل للخصم",
  "Disallowed (Art 28)": "غير قابل للخصم (المادة 28)",
  "Disallowed (Art 33)": "غير قابل للخصم (المادة 33)",
  "Docs awaiting approval": "مستندات بانتظار الاعتماد",
  "Donations to non-QPBE": "تبرعات لجهات غير مؤهلة",
  "Donations to non-qualifying bodies": "تبرعات لجهات غير مؤهلة",
  "Double entry validated before posting — Dr = Cr in AED": "التحقق من القيد المزدوج قبل الترحيل — المدين = الدائن بالدرهم",
  "Download all data as JSON": "تنزيل جميع البيانات بصيغة JSON",
  "Dr = Cr · immutable": "مدين = دائن · غير قابل للتعديل",
  "Dr = Cr ✓": "مدين = دائن ✓",
  "Drop file here or click to browse": "أفلت الملف هنا أو انقر للاستعراض",
  "Due in 30 days": "مستحق خلال 30 يومًا",
  "Due in 7 days": "مستحق خلال 7 أيام",
  "Due {date}": "الاستحقاق {date}",
  "Due {date} · ETR {r}%": "الاستحقاق {date} · المعدل الفعلي {r}%",
  "Due {date} · {n} days": "الاستحقاق {date} · {n} يومًا",
  "Duplicate & fraud scan": "فحص التكرار والاحتيال",
  "Duplicate invoice — cannot submit": "فاتورة مكررة — لا يمكن إرسالها",
  "Durable asset above capitalisation threshold → PPE (IT equipment), IAS 16.": "أصل معمّر فوق حد الرسملة ← ممتلكات ومعدات (معدات تقنية)، معيار IAS 16.",
  "E-invoice": "الفاتورة الإلكترونية",
  "E-invoice validated": "تم التحقق من الفاتورة الإلكترونية",
  "E-invoice {ref} — PINT AE": "الفاتورة الإلكترونية {ref} — PINT AE",
  "E-invoices delivered": "الفواتير الإلكترونية المسلّمة",
  "E-invoicing SME go-live": "بدء الفوترة الإلكترونية للمنشآت الصغيرة",
  "E-invoicing go-live": "بدء الفوترة الإلكترونية",
  "EINV": "فوترة إلكترونية",
  "EQUITY": "حقوق ملكية",
  "EXPENSE": "مصروف",
  "Each line needs a description and positive quantity": "كل سطر يحتاج إلى وصف وكمية موجبة",
  "Eligible for SBR": "مؤهل لإعفاء الأعمال الصغيرة",
  "Enable auto-approve for {o}": "تفعيل الاعتماد التلقائي لـ {o}",
  "Entertainment / personal — Art 53": "ضيافة / شخصي — المادة 53",
  "Entertainment disallowance": "عدم قابلية خصم الضيافة",
  "Entries": "القيود",
  "Equity": "حقوق الملكية",
  "Events": "الأحداث",
  "Every client at a glance — sort, filter or open": "كل العملاء في لمحة — رتّب أو صفِّ أو افتح",
  "Every document needs a human approver": "كل مستند يحتاج إلى اعتماد بشري",
  "Every line cites its legal basis": "كل سطر يستند إلى أساسه القانوني",
  "Exec. Reg. Art 59 — VERIFY": "اللائحة التنفيذية المادة 59 — للتحقق",
  "Exempt": "معفى",
  "Exempt supplies": "التوريدات المعفاة",
  "Expected AED {exp}, invoice shows AED {got}": "المتوقع {exp} درهم، والفاتورة تُظهر {got} درهم",
  "Expense treatment rules": "قواعد معاملة المصروفات",
  "Expenses": "المصروفات",
  "Explained from journal lines · drill down in General ledger": "مفسَّرة من أسطر القيود · التفاصيل في دفتر الأستاذ العام",
  "Export backup": "تصدير نسخة احتياطية",
  "Export · {c}": "تصدير · {c}",
  "Extracted": "مستخرجة",
  "Extracting supplier, TRN, amounts": "استخراج المورد والرقم الضريبي والمبالغ",
  "FDL 47/2022 · FY ending 31 Dec 2026 · YTD actuals to 30 Sep · deterministic rules engine (config {v})": "المرسوم بقانون 47/2022 · السنة المنتهية 31 ديسمبر 2026 · الفعلي حتى 30 سبتمبر · محرك قواعد قطعي (الإعداد {v})",
  "FIRM_ACCOUNTANT": "محاسب المكتب",
  "FIRM_PARTNER": "شريك المكتب",
  "FTA": "الهيئة الاتحادية للضرائب",
  "FY2026 estimate": "تقدير 2026",
  "Filter by type": "تصفية حسب النوع",
  "Financial statements": "القوائم المالية",
  "Fines & penalties": "الغرامات والجزاءات",
  "Fines and penalties — not deductible": "الغرامات والجزاءات — غير قابلة للخصم",
  "Firm": "المكتب",
  "Firm Accountant": "محاسب المكتب",
  "Firm Partner": "شريك المكتب",
  "Firm overview": "نظرة عامة على المكتب",
  "Food & beverage": "الأغذية والمشروبات",
  "For the nine months ended 30 September 2026 · AED": "للأشهر التسعة المنتهية في 30 سبتمبر 2026 · درهم",
  "Foreign supplier — reverse charge self-assessment": "مورد أجنبي — احتساب عكسي ذاتي",
  "Format: date,narrative,amount (negative = payment). MT940 / PDF parsing and Open-Finance feeds are on the roadmap.": "الصيغة: التاريخ,الوصف,المبلغ (السالب = دفعة). قراءة MT940 / PDF وربط التمويل المفتوح ضمن خطة التطوير.",
  "Found {n} posted entries matching \"{kw}\" (gross {amt}). Each links to its source document and audit trail.": "تم العثور على {n} قيدًا مرحّلًا يطابق «{kw}» (الإجمالي {amt}). كل قيد مرتبط بمستنده المصدر وسجل التدقيق.",
  "Fuel station vendor → Fuel and vehicle running. Input VAT recoverable if vehicle is used for business only.": "محطة وقود ← الوقود وتشغيل المركبات. ضريبة المدخلات قابلة للاسترداد إذا كانت المركبة للعمل فقط.",
  "GP": "مجمل الربح",
  "General ledger": "دفتر الأستاذ العام",
  "Generated from posted journals only · config {v} · FDL 8/2017": "مُنشأ من القيود المرحّلة فقط · الإعداد {v} · المرسوم بقانون 8/2017",
  "Generated from tax config — alerts at T-30 / T-14 / T-7 / T-1 (email & in-app; WhatsApp on roadmap)": "مُنشأ من إعدادات الضريبة — تنبيهات قبل 30/14/7/1 يوم (بريد إلكتروني وداخل التطبيق؛ واتساب لاحقًا)",
  "Good afternoon": "مساء الخير",
  "Good morning": "صباح الخير",
  "Goods / services": "سلع / خدمات",
  "Goods imported into the UAE": "السلع المستوردة إلى الدولة",
  "Google Ads (foreign)": "إعلانات Google (أجنبي)",
  "Government fee → Licences, visas and fees (generally outside VAT scope).": "رسوم حكومية ← الرخص والتأشيرات والرسوم (خارج نطاق الضريبة عادةً).",
  "Government fine → Fines and penalties (outside VAT scope; not CT-deductible, Art 33).": "غرامة حكومية ← الغرامات والجزاءات (خارج نطاق الضريبة؛ غير قابلة للخصم، المادة 33).",
  "Gross margin": "هامش الربح الإجمالي",
  "Gross profit": "مجمل الربح",
  "Health": "الصحة",
  "Health gauges": "مؤشرات الصحة المالية",
  "Hide": "إخفاء",
  "High": "مرتفع",
  "High risk": "مخاطر مرتفعة",
  "Higher = fewer auto-posts, more human review": "أعلى = ترحيل تلقائي أقل ومراجعة بشرية أكثر",
  "Hospitality for non-employees → Client entertainment.": "ضيافة لغير الموظفين ← ضيافة العملاء.",
  "Hospitality for non-employees → Client entertainment. Input VAT blocked (Exec. Reg. Art 53); CT 50% disallowed (Art 32).": "ضيافة لغير الموظفين ← ضيافة العملاء. ضريبة المدخلات محظورة (اللائحة المادة 53)؛ 50% غير قابلة للخصم لضريبة الشركات (المادة 32).",
  "How your numbers flow": "كيف تتدفق أرقامك",
  "Human": "بشري",
  "Humans approve": "الإنسان يعتمد",
  "I can answer questions about profit movements, revenue/expenses by month, overdue customers, VAT position, and expense searches (e.g. fuel, rent, entertainment). Try one of the suggestions.": "يمكنني الإجابة عن تغيّرات الربح، والإيرادات/المصروفات الشهرية، والعملاء المتأخرين، ووضع ضريبة القيمة المضافة، والبحث في المصروفات (مثل الوقود والإيجار والضيافة). جرّب أحد الاقتراحات.",
  "IFRS for SMEs presentation · {org} · period 1 Jan – 30 Sep 2026": "عرض وفق IFRS للمنشآت الصغيرة والمتوسطة · {org} · الفترة 1 يناير – 30 سبتمبر 2026",
  "Import CSV": "استيراد CSV",
  "Import bank statement (CSV)": "استيراد كشف بنكي (CSV)",
  "Import {n} lines": "استيراد {n} أسطر",
  "In inbox": "في صندوق الوارد",
  "Inbox": "صندوق الوارد",
  "Input VAT": "ضريبة المدخلات",
  "Input VAT recovery": "استرداد ضريبة المدخلات",
  "Insights": "التحليلات",
  "Integrity": "السلامة",
  "Invalid backup file": "ملف نسخة احتياطية غير صالح",
  "Invalid tax invoice": "فاتورة ضريبية غير صالحة",
  "Invoice": "الفاتورة",
  "Invoice date": "تاريخ الفاتورة",
  "Invoice no.": "رقم الفاتورة",
  "Invoice number (BT-1) is mandatory": "رقم الفاتورة (BT-1) إلزامي",
  "Invoice older than 12 months": "فاتورة أقدم من 12 شهرًا",
  "Invoice {ref} issued & posted": "تم إصدار الفاتورة {ref} وترحيلها",
  "Invoiced": "المفوتر",
  "Invoiced YTD": "المفوتر منذ بداية السنة",
  "Invoiced by month": "الفوترة حسب الشهر",
  "Invoices": "الفواتير",
  "Issue & post invoice": "إصدار الفاتورة وترحيلها",
  "Issue date (BT-2) is mandatory": "تاريخ الإصدار (BT-2) إلزامي",
  "Issue date cannot be in the future": "لا يمكن أن يكون تاريخ الإصدار في المستقبل",
  "Item": "البند",
  "Journal approved": "تم اعتماد القيد",
  "Journal entries": "قيود اليومية",
  "Journal reversed": "تم عكس القيد",
  "Journal saved": "تم حفظ القيد",
  "Journals": "القيود",
  "Jump to…": "انتقل إلى…",
  "Key ratios computed from the ledger": "نسب رئيسية محسوبة من دفتر الأستاذ",
  "LIABILITY": "التزام",
  "LICENCE": "رخصة",
  "Laptop purchase": "شراء حاسوب محمول",
  "Legal reference": "المرجع القانوني",
  "Less:": "يُطرح:",
  "Liabilities": "الخصوم",
  "Licence / WPS": "رخصة / نظام حماية الأجور",
  "Live from posted ledger · YTD Jan–Sep 2026": "مباشر من الدفتر المرحّل · من يناير حتى سبتمبر 2026",
  "Live pipeline — hover a step to trace it, click to open": "مسار مباشر — مرّر على خطوة لتتبّعها وانقر للفتح",
  "Live · stored locally · config uae-2026.09": "مباشر · مخزّن محليًا · الإعداد uae-2026.09",
  "Load a previously exported file": "تحميل ملف مُصدَّر سابقًا",
  "Local data": "البيانات المحلية",
  "Low": "منخفض",
  "Low risk": "مخاطر منخفضة",
  "MANUAL": "يدوي",
  "Main navigation": "التنقل الرئيسي",
  "Maker-checker": "مُعِدّ ومُراجِع",
  "Maker-checker queue": "قائمة المُعِدّ والمُراجِع",
  "Maker-checker: preparer cannot approve.": "مبدأ المُعِدّ والمُراجِع: لا يمكن للمُعِدّ الاعتماد.",
  "Maker-checker: the preparer cannot approve their own entry.": "مبدأ المُعِدّ والمُراجِع: لا يمكن للمُعِدّ اعتماد قيده.",
  "Maker-checker: you prepared this — a different approver (e.g. Client Owner) must approve.": "مبدأ المُعِدّ والمُراجِع: أنت من أعدّ هذا — يجب أن يعتمده شخص آخر (مثل مالك العميل).",
  "Mandatory for SMEs (< AED 50m): appoint ASP by 31 Mar 2027, go-live 1 Jul 2027 — VERIFY.": "إلزامي للمنشآت (< 50 مليون درهم): تعيين مزوّد الخدمة بحلول 31 مارس 2027 والبدء 1 يوليو 2027 — للتحقق.",
  "Manual journal": "قيد يدوي",
  "Master console across every client — prepared by AI, reviewed by your team.": "لوحة رئيسية لجميع العملاء — يُعدّها الذكاء الاصطناعي ويراجعها فريقك.",
  "Match / AI suggestion": "المطابقة / اقتراح الذكاء الاصطناعي",
  "Matched": "مطابق",
  "Matches {ref} captured {date}": "يطابق {ref} الملتقطة في {date}",
  "Max amount per document": "الحد الأقصى لكل مستند",
  "Medium": "متوسط",
  "Medium risk": "مخاطر متوسطة",
  "Memo": "البيان",
  "Minimum AI confidence: {n}%": "الحد الأدنى لثقة الذكاء الاصطناعي: {n}%",
  "Missing": "مفقود",
  "MoM": "شهريًا",
  "Money in": "الوارد",
  "Money out": "الصادر",
  "Monthly revenue by client, stacked": "الإيرادات الشهرية حسب العميل، تراكمية",
  "Monthly, AED — from posted journals": "شهريًا، بالدرهم — من القيود المرحّلة",
  "Multiple items": "عدة بنود",
  "NOT_SENT": "لم تُرسل",
  "NP": "صافي الربح",
  "Narration": "البيان",
  "Narrative": "الوصف",
  "Natural-language questions answered from this tenant's posted ledger only — the query is always shown.": "أسئلة بلغة طبيعية يُجاب عنها من الدفتر المرحّل لهذه المنشأة فقط — مع عرض الاستعلام دائمًا.",
  "Needs human approval (auto-approve off).": "يحتاج إلى اعتماد بشري (الاعتماد التلقائي متوقف).",
  "Needs human approval (rule: ≤ AED {max}, ≥ {c}%, low risk).": "يحتاج إلى اعتماد بشري (القاعدة: ≤ {max} درهم، ≥ {c}%، مخاطر منخفضة).",
  "Net": "الصافي",
  "Net VAT due": "صافي الضريبة المستحقة",
  "Net VAT payable": "صافي الضريبة المستحقة",
  "Net VAT position for the current quarter is payable: {amt}.": "صافي ضريبة القيمة المضافة للربع الحالي مستحق الدفع: {amt}.",
  "Net VAT position for the current quarter is refundable: {amt}.": "صافي ضريبة القيمة المضافة للربع الحالي قابل للاسترداد: {amt}.",
  "Net margin": "هامش صافي الربح",
  "Net payable": "الصافي المستحق",
  "Net profit": "صافي الربح",
  "Net profit YTD": "صافي الربح منذ بداية السنة",
  "Net profit decreased by {amt} in {cur} vs {prev} ({a} → {b}). Main drivers:": "انخفض صافي الربح بمقدار {amt} في {cur} مقارنة بـ {prev} ({a} ← {b}). أهم الأسباب:",
  "Net profit increased by {amt} in {cur} vs {prev} ({a} → {b}). Main drivers:": "ارتفع صافي الربح بمقدار {amt} في {cur} مقارنة بـ {prev} ({a} ← {b}). أهم الأسباب:",
  "New tax invoice": "فاتورة ضريبية جديدة",
  "Next 12 weeks · hover a cell for details": "الأسابيع الـ12 القادمة · مرّر على خلية للتفاصيل",
  "Next VAT return": "إقرار ضريبة القيمة المضافة التالي",
  "Next filing": "التقديم التالي",
  "Next page": "الصفحة التالية",
  "No UAE TRN expected; account for output & input VAT (Box 3 & 10)": "لا يُتوقع رقم ضريبي إماراتي؛ تُحتسب ضريبة المخرجات والمدخلات (الخانتان 3 و10)",
  "No VAT (out of scope)": "بدون ضريبة (خارج النطاق)",
  "No activity yet in this session — capture an invoice or switch roles.": "لا يوجد نشاط بعد في هذه الجلسة — التقط فاتورة أو بدّل الدور.",
  "No approvals": "لا اعتمادات",
  "No customers are over that age bucket.": "لا يوجد عملاء تجاوزوا هذه المدة.",
  "No deadlines": "لا مواعيد نهائية",
  "No deadlines in this range.": "لا مواعيد نهائية في هذه الفترة.",
  "No documents match. Upload one or try a sample above.": "لا توجد مستندات مطابقة. ارفع مستندًا أو جرّب نموذجًا أعلاه.",
  "No edits or deletes": "لا تعديل ولا حذف",
  "No matches": "لا نتائج",
  "No rows match your filters.": "لا توجد صفوف تطابق عوامل التصفية.",
  "No standard-rated sales this quarter.": "لا مبيعات خاضعة للنسبة الأساسية هذا الربع.",
  "No strong pattern matched — defaulted to Office supplies and IT. Needs human review.": "لم يُطابق نمط واضح — صُنّف افتراضيًا كمستلزمات مكتبية وتقنية. يحتاج إلى مراجعة بشرية.",
  "No transactions in this box.": "لا معاملات في هذه الخانة.",
  "Not a duplicate of an earlier invoice": "ليست مكررة لفاتورة سابقة",
  "Not eligible for SBR": "غير مؤهل لإعفاء الأعمال الصغيرة",
  "Not enough monthly history yet.": "لا يوجد سجل شهري كافٍ بعد.",
  "Nothing here yet.": "لا شيء هنا بعد.",
  "Nothing is posted to the ledger without passing AI, deterministic rules and human approval.": "لا يُرحَّل أي شيء إلى الدفتر دون المرور بالذكاء الاصطناعي والقواعد القطعية والاعتماد البشري.",
  "OPENING": "افتتاحي",
  "Of AED 3m SBR ceiling": "من سقف الإعفاء البالغ 3 ملايين درهم",
  "Office consumables / software → Office supplies and IT.": "مستهلكات مكتبية / برمجيات ← المستلزمات المكتبية والتقنية.",
  "Office rent — Sep 2026": "إيجار المكتب — سبتمبر 2026",
  "Only firm users can reverse posted journals.": "يمكن لمستخدمي المكتب فقط عكس القيود المرحّلة.",
  "Open": "فتح",
  "Open AR": "المدينون المفتوحون",
  "Open menu": "فتح القائمة",
  "Open risk flags": "مؤشرات المخاطر المفتوحة",
  "Operating expenses": "المصروفات التشغيلية",
  "Operating expenses YTD · hover a slice": "المصروفات التشغيلية منذ بداية السنة · مرّر على جزء",
  "Optional for unregistered customers": "اختياري للعملاء غير المسجلين",
  "Or try a sample invoice": "أو جرّب فاتورة نموذجية",
  "Other": "أخرى",
  "Other income": "إيرادات أخرى",
  "Other opex": "مصروفات أخرى",
  "Out by {amt}": "فرق {amt}",
  "Out of balance": "غير متوازنة",
  "Output VAT": "ضريبة المخرجات",
  "Output vs recoverable input, AED": "المخرجات مقابل المدخلات القابلة للاسترداد، بالدرهم",
  "Outstanding": "المستحق",
  "Overdue": "متأخر السداد",
  "P&L, balance sheet and trial balance in real time": "الأرباح والخسائر والميزانية وميزان المراجعة لحظيًا",
  "PAID": "مدفوعة",
  "PDF · image · XML · WhatsApp": "PDF · صورة · XML · واتساب",
  "PDF, image, e-invoice XML, email or WhatsApp forward": "PDF أو صورة أو فاتورة XML أو بريد إلكتروني أو واتساب",
  "PENDING": "قيد الاعتماد",
  "PINT AE": "PINT AE",
  "PINT AE pre-validation failed": "فشل التحقق المسبق من PINT AE",
  "POC stores everything in this browser's localStorage — no server, no database": "النموذج الأولي يخزّن كل شيء في التخزين المحلي للمتصفح — بلا خادم ولا قاعدة بيانات",
  "POC: extraction is simulated from the file name (try \"uber.pdf\", \"rent.pdf\")": "نموذج أولي: يُحاكى الاستخراج من اسم الملف (جرّب «uber.pdf» أو «rent.pdf»)",
  "POSTED": "مرحّل",
  "PURCHASE": "مشتريات",
  "Page": "صفحة",
  "Pagination": "التنقل بين الصفحات",
  "Parameter": "المعامل",
  "Payable / (refundable) tax": "الضريبة المستحقة / (المستردة)",
  "Payable amount = line extension + tax total": "المبلغ المستحق = مجموع الأسطر + إجمالي الضريبة",
  "Pending approval": "بانتظار الاعتماد",
  "Pending approvals": "اعتمادات معلّقة",
  "Pending approvals: {n}": "اعتمادات معلّقة: {n}",
  "Per-tenant AI approval thresholds, tax configuration and local data management": "حدود اعتماد الذكاء الاصطناعي لكل منشأة وإعدادات الضريبة وإدارة البيانات المحلية",
  "Personal / non-business expenditure": "مصروفات شخصية / غير متعلقة بالعمل",
  "Personal expenses": "المصروفات الشخصية",
  "Personal-nature spend → Non-deductible. Input VAT blocked; CT disallowed.": "إنفاق ذو طابع شخصي ← غير قابل للخصم. ضريبة المدخلات محظورة؛ غير مسموح لضريبة الشركات.",
  "Pilot cohort · Feb 2027": "الدفعة التجريبية · فبراير 2027",
  "Place of supply (emirate)": "مكان التوريد (الإمارة)",
  "Portfolio revenue": "إيرادات المحفظة",
  "Possible fake VAT charge — do not claim": "احتمال ضريبة وهمية — لا تُطالب بها",
  "Post to {a}": "ترحيل إلى {a}",
  "Posted": "مرحّل",
  "Posted as {id} — P&L, Balance Sheet and VAT 201 updated": "رُحّل برقم {id} — تم تحديث الأرباح والخسائر والميزانية وإقرار VAT 201",
  "Posted to ledger": "مرحّل إلى الدفتر",
  "Posted {ref} to the ledger": "تم ترحيل {ref} إلى الدفتر",
  "Posts Dr Receivables / Cr Revenue & VAT output on issue": "يُرحّل عند الإصدار: مدين المدينون / دائن الإيرادات وضريبة المخرجات",
  "Pre-validation (local rules, before ASP)": "تحقق مسبق (قواعد محلية قبل مزوّد الخدمة)",
  "Prepared / approved": "أعدّه / اعتمده",
  "Prepared by": "أعدّه",
  "Present": "موجود",
  "Previous page": "الصفحة السابقة",
  "Print": "طباعة",
  "Production: UAE-region PostgreSQL with RLS, nightly encrypted backups (see ARCHITECTURE.md).": "الإنتاج: PostgreSQL داخل الإمارات مع عزل على مستوى الصفوف ونسخ احتياطية مشفرة ليلية (انظر ARCHITECTURE.md).",
  "Professional services": "الخدمات المهنية",
  "Professional services → Professional fees.": "خدمات مهنية ← الأتعاب المهنية.",
  "Profit & loss": "الأرباح والخسائر",
  "Profit after estimated tax": "الربح بعد الضريبة التقديرية",
  "Profit before tax": "الربح قبل الضريبة",
  "Profit for the period": "ربح الفترة",
  "Profit walk": "مسار الربح",
  "Profit → tax bridge": "من الربح إلى الضريبة",
  "Purchase invoices": "فواتير المشتريات",
  "Purchase of goods for resale → Inventory (expensed to COGS on sale).": "شراء سلع لإعادة البيع ← المخزون (يُحمَّل على تكلفة المبيعات عند البيع).",
  "Purchase of goods for resale → Inventory.": "شراء سلع لإعادة البيع ← المخزون.",
  "QFZP": "شخص مؤهل في منطقة حرة",
  "Qty": "الكمية",
  "Qualifying Free Zone Person": "شخص مؤهل في منطقة حرة",
  "Querying ledger…": "جارٍ الاستعلام من الدفتر…",
  "REJECTED": "مرفوض",
  "REVENUE": "إيراد",
  "REVERSAL": "عكس قيد",
  "REVERSED": "معكوس",
  "REVIEW": "قيد المراجعة",
  "Read-only · tenant-scoped · every answer shows its query": "قراءة فقط · ضمن المنشأة · كل إجابة تعرض استعلامها",
  "Reading document (OCR, EN/AR)": "قراءة المستند (OCR، عربي/إنجليزي)",
  "Reading {f}…": "جارٍ قراءة {f}…",
  "Receipt": "سند قبض",
  "Receipt recorded for {ref}": "تم تسجيل التحصيل لـ {ref}",
  "Receivables ageing": "أعمار الذمم المدينة",
  "Receive": "تحصيل",
  "Recipient name/TRN (full tax invoice > AED 10,000)": "اسم المستلم/رقمه الضريبي (فاتورة كاملة > 10,000 درهم)",
  "Reconciled": "تمت التسوية",
  "Recoverable VAT": "الضريبة القابلة للاسترداد",
  "Recoverable — Box 9": "قابلة للاسترداد — الخانة 9",
  "Ref": "المرجع",
  "Regime": "النظام",
  "Reject": "رفض",
  "Rejected": "مرفوض",
  "Rejected {ref}": "تم رفض {ref}",
  "Rejected — not posted": "مرفوض — لم يُرحّل",
  "Remove line": "حذف السطر",
  "Reports": "التقارير",
  "Reset": "إعادة تعيين",
  "Reset demo data": "إعادة تعيين بيانات العرض",
  "Reset demo data?": "إعادة تعيين بيانات العرض؟",
  "Restore backup": "استعادة نسخة احتياطية",
  "Return boxes populate automatically with drill-down": "تُعبّأ خانات الإقرار تلقائيًا مع إمكانية التفصيل",
  "Revenue": "الإيرادات",
  "Revenue YTD": "الإيرادات منذ بداية السنة",
  "Revenue by month": "الإيرادات حسب الشهر",
  "Revenue by month:": "الإيرادات حسب الشهر:",
  "Revenue collected": "الإيرادات المحصّلة",
  "Revenue to net profit, YTD": "من الإيرادات إلى صافي الربح، منذ بداية السنة",
  "Revenue under management": "الإيرادات تحت الإدارة",
  "Revenue vs expenses": "الإيرادات مقابل المصروفات",
  "Revenue ≤ AED 3m in current & all prior periods": "إيرادات ≤ 3 ملايين درهم في الفترة الحالية وجميع الفترات السابقة",
  "Reverse": "عكس",
  "Reverse charge — Box 3 & 10": "احتساب عكسي — الخانتان 3 و10",
  "Reverses {id}": "يعكس {id}",
  "Ride-hailing / travel vendor keywords → Transportation and travel.": "كلمات مزوّدي النقل/السفر ← النقل والسفر.",
  "Risk": "المخاطر",
  "Round amounts are an audit red flag": "المبالغ المقرّبة مؤشر تحذيري للتدقيق",
  "Round-sum amount": "مبلغ مقرّب",
  "Rows per page": "صفوف في الصفحة",
  "Rules & approval": "القواعد والاعتماد",
  "Rules engine — not AI": "محرك قواعد — وليس ذكاءً اصطناعيًا",
  "Rules validate": "القواعد تتحقق",
  "Rules-based bridge from accounting profit to taxable income": "ربط قائم على القواعد من الربح المحاسبي إلى الدخل الخاضع للضريبة",
  "Running balance, posted journals": "الرصيد المتراكم، القيود المرحّلة",
  "SALE": "مبيعات",
  "SBR": "إعفاء الأعمال الصغيرة",
  "SBR elected": "تم اختيار إعفاء الأعمال الصغيرة",
  "SBR elected but eligibility FAILS — computed under the standard regime.": "تم اختيار إعفاء الأعمال الصغيرة لكن الأهلية غير متحققة — احتُسبت وفق النظام العادي.",
  "SBR ends {d} — VERIFY": "ينتهي الإعفاء {d} — للتحقق",
  "SBR last period end": "آخر فترة لإعفاء الأعمال الصغيرة",
  "SBR revenue limit": "حد إيرادات إعفاء الأعمال الصغيرة",
  "SBR — nil": "إعفاء الأعمال الصغيرة — صفر",
  "SENT": "مُرسلة",
  "Salaries, rent, utilities": "الرواتب والإيجار والمرافق",
  "Sales & e-invoicing": "المبيعات والفوترة الإلكترونية",
  "Sales invoice issued": "صدرت فاتورة مبيعات",
  "Sales invoices": "فواتير المبيعات",
  "Save journal": "حفظ القيد",
  "Search": "بحث",
  "Search pages and clients…": "ابحث في الصفحات والعملاء…",
  "Search supplier or invoice no.": "ابحث بالمورد أو رقم الفاتورة",
  "Search…": "بحث…",
  "Select or upload an invoice": "اختر فاتورة أو ارفعها",
  "Seller": "البائع",
  "Seller ASP": "مزوّد البائع",
  "Seller TRN (BT-31) must be a valid 15-digit TRN": "يجب أن يكون الرقم الضريبي للبائع (BT-31) صالحًا من 15 رقمًا",
  "Send": "إرسال",
  "Sequential invoice number": "رقم فاتورة تسلسلي",
  "Session": "الجلسة",
  "Settings": "الإعدادات",
  "Show all fuel expenses claimed": "اعرض جميع مصروفات الوقود المطالب بها",
  "Show entertainment expenses": "اعرض مصروفات الضيافة",
  "Single source of truth — every report reads only posted journals": "مصدر واحد للحقيقة — كل التقارير تقرأ القيود المرحّلة فقط",
  "Single source of truth. Posted journals are immutable — corrections by reversal only.": "مصدر واحد للحقيقة. القيود المرحّلة غير قابلة للتعديل — التصحيح بالعكس فقط.",
  "Small Business Relief": "إعفاء الأعمال الصغيرة",
  "Small Business Relief elected — taxable income treated as nil. Losses in SBR periods cannot be carried forward.": "تم اختيار إعفاء الأعمال الصغيرة — يُعامل الدخل الخاضع للضريبة كصفر. لا يمكن ترحيل الخسائر في فترات الإعفاء.",
  "Small Business Relief monitor": "متابعة إعفاء الأعمال الصغيرة",
  "Source": "المصدر",
  "Standard (0% / 9%)": "عادي (0% / 9%)",
  "Standard 5%": "أساسي 5%",
  "Standard CT": "ضريبة شركات عادية",
  "Standard rated expenses": "المصروفات الخاضعة للنسبة الأساسية",
  "Standard rated supplies — {e}": "التوريدات الخاضعة للنسبة الأساسية — {e}",
  "Standard-rated sales by emirate": "المبيعات الخاضعة للنسبة الأساسية حسب الإمارة",
  "Start again from the seeded clients": "البدء من جديد بالعملاء التجريبيين",
  "Statement lines": "أسطر الكشف",
  "Statement lines auto-matched to ledger entries": "أسطر الكشف تُطابق تلقائيًا مع قيود الدفتر",
  "Statement of financial position": "قائمة المركز المالي",
  "Statement of profit or loss": "قائمة الأرباح أو الخسائر",
  "Status": "الحالة",
  "Submit (auto-approve)": "إرسال (اعتماد تلقائي)",
  "Submit for approval": "إرسال للاعتماد",
  "Submitted": "مُرسلة",
  "Submitted for approval": "أُرسل للاعتماد",
  "Supplier": "المورد",
  "Supplier TRN": "الرقم الضريبي للمورد",
  "Supplier TRN present & valid format (15 digits)": "الرقم الضريبي للمورد موجود وصيغته صحيحة (15 رقمًا)",
  "Supplier invoices uploaded or forwarded — read by Document AI": "فواتير الموردين المرفوعة أو المُعاد توجيهها — يقرؤها الذكاء الاصطناعي",
  "Supplier is outside the UAE → reverse charge applies (Art 48).": "المورد خارج الدولة ← يُطبق الاحتساب العكسي (المادة 48).",
  "Supplier name": "اسم المورد",
  "Supplies subject to reverse charge": "التوريدات الخاضعة للاحتساب العكسي",
  "Supplies subject to reverse charge (input)": "التوريدات الخاضعة للاحتساب العكسي (مدخلات)",
  "Switch role": "تبديل الدور",
  "TB CSV": "ميزان المراجعة CSV",
  "TFS Plus Tax & Accountancy": "تي إف إس بلس للضرائب والمحاسبة",
  "TFS Plus Tax & Accountancy LLC · FTA-registered tax agency": "تي إف إس بلس للضرائب والمحاسبة ذ.م.م · وكيل ضريبي مسجّل لدى الهيئة",
  "TRN missing — input VAT not recoverable": "الرقم الضريبي مفقود — ضريبة المدخلات غير قابلة للاسترداد",
  "TRN must be 15 digits starting with 1": "يجب أن يتكون الرقم الضريبي من 15 رقمًا ويبدأ بـ 1",
  "TRN {trn}": "الرقم الضريبي {trn}",
  "Tax": "الضرائب",
  "Tax adjustments (add-backs)": "التعديلات الضريبية (الإضافات)",
  "Tax configuration": "إعدادات الضريبة",
  "Tax invoices issued": "الفواتير الضريبية الصادرة",
  "Tax period": "الفترة الضريبية",
  "Tax risk": "المخاطر الضريبية",
  "Tax-inclusive, AED": "شاملة الضريبة، بالدرهم",
  "Taxable": "الخاضع للضريبة",
  "Taxable income": "الدخل الخاضع للضريبة",
  "Taxable income bridge": "تسوية الدخل الخاضع للضريبة",
  "Taxable value": "القيمة الخاضعة للضريبة",
  "Taxable value stated": "القيمة الخاضعة للضريبة مذكورة",
  "Taxed at 9%": "خاضع لنسبة 9%",
  "This session": "هذه الجلسة",
  "Time": "الوقت",
  "To review": "للمراجعة",
  "Top operating expenses in {m}:": "أعلى المصروفات التشغيلية في {m}:",
  "Total": "الإجمالي",
  "Total = taxable value + VAT": "الإجمالي = القيمة الخاضعة + الضريبة",
  "Total AED": "الإجمالي بالدرهم",
  "Total assets": "إجمالي الأصول",
  "Total equity": "إجمالي حقوق الملكية",
  "Total liabilities": "إجمالي الخصوم",
  "Total liabilities and equity": "إجمالي الخصوم وحقوق الملكية",
  "Totals": "الإجماليات",
  "Trade licence renewal": "تجديد الرخصة التجارية",
  "Trading": "تجارة",
  "Trading goods": "بضائع تجارية",
  "Trial balance": "ميزان المراجعة",
  "Trial balance exported": "تم تصدير ميزان المراجعة",
  "UNPAID": "غير مدفوعة",
  "Uber trip — Airport": "رحلة أوبر — المطار",
  "Unbalanced": "غير متوازن",
  "Unit price": "سعر الوحدة",
  "Unreconciled": "غير مسوّاة",
  "Unregistered": "غير مسجّل",
  "Unusual for B2B supplier": "غير معتاد لمورد بين الشركات",
  "Upcoming deadlines": "المواعيد النهائية القادمة",
  "Upload an invoice": "رفع فاتورة",
  "Upload → AI extraction → Article 59 check → fraud & duplicate scan → classification → journal → approval": "رفع ← استخراج ذكي ← فحص المادة 59 ← فحص الاحتيال والتكرار ← التصنيف ← القيد ← الاعتماد",
  "User": "المستخدم",
  "Users": "المستخدمون",
  "Utility / telecom provider → Utilities and telecom.": "مزوّد مرافق/اتصالات ← المرافق والاتصالات.",
  "VALIDATED": "تم التحقق",
  "VAT": "ضريبة القيمة المضافة",
  "VAT / CT filing": "تقديم ضريبة القيمة المضافة / الشركات",
  "VAT 201": "إقرار VAT 201",
  "VAT 201 return": "إقرار ضريبة القيمة المضافة 201",
  "VAT 201 · Q3": "إقرار 201 · الربع الثالث",
  "VAT 5%": "الضريبة 5%",
  "VAT = 5% of taxable value": "الضريبة = 5% من القيمة الخاضعة",
  "VAT Q3": "الضريبة · الربع 3",
  "VAT Q3 · {n} days": "ضريبة الربع الثالث · {n} يومًا",
  "VAT by quarter": "الضريبة حسب الربع",
  "VAT charged by supplier without TRN": "ضريبة محمّلة من مورد بلا رقم ضريبي",
  "VAT mandatory registration": "حد التسجيل الإلزامي",
  "VAT on expenses and all other inputs": "الضريبة على المصروفات وجميع المدخلات الأخرى",
  "VAT on sales and all other outputs": "الضريبة على المبيعات وجميع المخرجات الأخرى",
  "VAT payable · Q3": "الضريبة المستحقة · الربع 3",
  "VAT return due": "موعد إقرار الضريبة",
  "VAT return {q} — file & pay": "إقرار ضريبة القيمة المضافة {q} — التقديم والسداد",
  "VAT standard rate": "النسبة الأساسية للضريبة",
  "VAT tax code": "رمز ضريبة القيمة المضافة",
  "VAT treatment": "المعاملة الضريبية",
  "VERIFY": "للتحقق",
  "Valid tax invoice": "فاتورة ضريبية صالحة",
  "Validate & transmit via ASP (sandbox)": "تحقق وأرسل عبر مزوّد الخدمة (تجريبي)",
  "Validated": "تم التحقق",
  "Value": "القيمة",
  "Verified": "تم التحقق",
  "Verifying TRN format": "التحقق من صيغة الرقم الضريبي",
  "Version {v} · last verified {d} · rules are data, not code": "الإصدار {v} · آخر تحقق {d} · القواعد بيانات وليست شيفرة",
  "WPS": "حماية الأجور",
  "WPS salary run ({m})": "صرف الرواتب عبر نظام حماية الأجور ({m})",
  "Waterfall from accounting profit to corporate tax payable": "شلال من الربح المحاسبي إلى ضريبة الشركات المستحقة",
  "Weekend-dated invoice": "فاتورة بتاريخ عطلة نهاية الأسبوع",
  "What is my VAT position?": "ما هو وضع ضريبة القيمة المضافة؟",
  "Where the money goes": "أين تذهب الأموال",
  "Which customers are over 30 days?": "أي العملاء متأخرون أكثر من 30 يومًا؟",
  "Why did profit decrease this month?": "لماذا انخفض الربح هذا الشهر؟",
  "Why:": "السبب:",
  "Within auto-approve rule: ≤ AED {max}, ≥ {c}% confidence, low risk.": "ضمن قاعدة الاعتماد التلقائي: ≤ {max} درهم، ثقة ≥ {c}%، مخاطر منخفضة.",
  "Within tenant thresholds": "ضمن حدود المنشأة",
  "Workload per accountant": "عبء العمل لكل محاسب",
  "Workspace": "مساحة العمل",
  "Wrong VAT + no TRN": "ضريبة خاطئة + بلا رقم ضريبي",
  "XML copied": "تم نسخ XML",
  "Your role cannot approve — switch role in the sidebar.": "دورك لا يسمح بالاعتماد — بدّل الدور من الشريط الجانبي.",
  "Your role cannot approve.": "دورك لا يسمح بالاعتماد.",
  "Your role cannot approve. Switch to Partner or Owner.": "دورك لا يسمح بالاعتماد. بدّل إلى الشريك أو المالك.",
  "Zero rated supplies": "التوريدات الخاضعة لنسبة الصفر",
  "Zero-rated": "نسبة صفر",
  "Zero-rated lines to UAE buyers need an export/zero-rating justification": "الأسطر بنسبة صفر لمشترين داخل الدولة تحتاج إلى مسوّغ تصدير/نسبة صفرية",
  "e.g. Accrual for audit fee": "مثال: استحقاق أتعاب التدقيق",
  "e.g. Why did profit decrease this month?": "مثال: لماذا انخفض الربح هذا الشهر؟",
  "in {n}d": "خلال {n} يوم",
  "journals": "قيود",
  "lines matched to ledger": "سطر مطابق مع الدفتر",
  "prior period": "الفترة السابقة",
  "{amt} input VAT at risk": "{amt} ضريبة مدخلات معرّضة للخطر",
  "{a}/{b} checks passed · risk score {s}/100": "{a}/{b} فحوص ناجحة · درجة المخاطر {s}/100",
  "{a}–{b} of {n}": "{a}–{b} من {n}",
  "{n} adjustment(s)": "{n} تعديلات",
  "{n} approvals": "{n} اعتمادات",
  "{n} bank line(s) imported": "تم استيراد {n} سطر بنكي",
  "{n} bank line(s) matched": "تمت مطابقة {n} سطر بنكي",
  "{n} bank lines": "{n} أسطر بنكية",
  "{n} corporate tax adjustment(s) required": "{n} تعديلات مطلوبة لضريبة الشركات",
  "{n} customer invoice(s) are past {d} days, totalling {amt}.": "{n} فاتورة عملاء تجاوزت {d} يومًا، بإجمالي {amt}.",
  "{n} days": "{n} يومًا",
  "{n} deadlines": "{n} مواعيد نهائية",
  "{n} in review": "{n} قيد المراجعة",
  "{n} invoice(s) with missing / invalid TRN": "{n} فاتورة برقم ضريبي مفقود / غير صالح",
  "{n} invoices": "{n} فاتورة",
  "{n} invoices past due": "{n} فاتورة متأخرة",
  "{n} journals": "{n} قيدًا",
  "{n} pending": "{n} معلّقة",
  "{n} posted": "{n} مرحّلة",
  "{n} results": "{n} نتيجة",
  "{n} unpaid": "{n} غير مدفوعة",
  "{n} unreconciled": "{n} غير مسوّاة",
  "{n} unreconciled bank line(s)": "{n} أسطر بنكية غير مسوّاة",
  "{n} via ASP · go-live 1 Jul 2027": "{n} عبر مزوّد الخدمة · البدء 1 يوليو 2027",
  "{n}% confidence": "ثقة {n}%",
  "{n}d": "{n} يوم",
  "{n}d overdue": "متأخرة {n} يوم",
  "{ref} posted": "تم ترحيل {ref}",
  "{ref} reversed": "تم عكس {ref}",
  "{ref} sent for approval (maker-checker)": "أُرسل {ref} للاعتماد (مُعِدّ ومُراجِع)",
};
